apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformsapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformsapi
  template:
    metadata:
      labels:
        app: platformsapi
    spec:
      containers:
      - name: platformsapi
        image: piotrkowalski93/platformsservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: platformsapi-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformsapi
  ports:
  - name: platformsapi 
    protocol: TCP
    port: 80
    targetPort: 80
  - name: plafromgrpc
    protocol: TCP
    port: 666
    targetPort: 666