apiVersion: v1
kind: Service
metadata:
  name: platformsapi-srv
spec:
  type: NodePort
  selector:
    app: platformsapi
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
